# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58eea85e61a2ee1b4cb1c9781d3a94c3aeb6e3699d76568739a94adec5e770e0586f828c7f9230fd9e8093659e30baa2456f57952b9922d4905c279b3db12b3f

test:
  secret_key_base: fbaa6b14ad4effc2af96c526fd41b40365555fcd4fdee64e7eb3a5d14dc3ca96182815475aad65b9a94b82530a0ae22da4ae373cfaec7ca4c4774427dd42cffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
